language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - python setup.py develop
  - pip install pytest coverage hypothesis codecov
after_success:
  - codecov
script: ./runtests.sh
