language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pytest coverage hypothesis codecov
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install mypy; fi
  - python setup.py install
script: ./runtests.sh
after_success:
  - codecov
